// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOYfieIF6eBwv-462j2QrZj1xSyUfPN_k',
    appId: '1:314936721041:web:324c2a46eb6bf916fac930',
    messagingSenderId: '314936721041',
    projectId: 'taskit-6d9b9',
    authDomain: 'taskit-6d9b9.firebaseapp.com',
    storageBucket: 'taskit-6d9b9.appspot.com',
    measurementId: 'G-BXBHJQVM87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhg0yJjf3ti_qCHsKwIj9kYFGXV6NUHeo',
    appId: '1:314936721041:android:887420e254abddbefac930',
    messagingSenderId: '314936721041',
    projectId: 'taskit-6d9b9',
    storageBucket: 'taskit-6d9b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRfL3BR__kgQsXyjvxNXn-qrxbs6VHn5w',
    appId: '1:314936721041:ios:f75d959a90e3ec25fac930',
    messagingSenderId: '314936721041',
    projectId: 'taskit-6d9b9',
    storageBucket: 'taskit-6d9b9.appspot.com',
    iosBundleId: 'com.example.taskIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRfL3BR__kgQsXyjvxNXn-qrxbs6VHn5w',
    appId: '1:314936721041:ios:f75d959a90e3ec25fac930',
    messagingSenderId: '314936721041',
    projectId: 'taskit-6d9b9',
    storageBucket: 'taskit-6d9b9.appspot.com',
    iosBundleId: 'com.example.taskIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOYfieIF6eBwv-462j2QrZj1xSyUfPN_k',
    appId: '1:314936721041:web:541908fb3b548556fac930',
    messagingSenderId: '314936721041',
    projectId: 'taskit-6d9b9',
    authDomain: 'taskit-6d9b9.firebaseapp.com',
    storageBucket: 'taskit-6d9b9.appspot.com',
    measurementId: 'G-LWTK3R1NE9',
  );
}